on:
    - push
jobs:
    compile:
        strategy:
            matrix:
                kotlin-version: ["2.0.20", "2.0.21", "2.1.0-RC2", "1.9.25", "1.8.21"]
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17 for x64
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   uses: gradle/actions/setup-gradle@v4
            -   run: |
                    ./gradlew build
                env:
                    KOTLIN_VERSION: ${{ matrix.kotlin-version }}
                name: This will infinitely hang
        runs-on: ubuntu-latest

